Domaineinstellungen unter yrewrite
FriendsOfREDAXO/yrewrite_domain_settings pull request #29
Opened 2022-12-08 16:05 UTC by anveno

Die Domaineinstellungen erscheinen dadurch nicht mehr unter "Tabellen", sondern als Reiter bei "Addons" > "YRewrite".

siehe auch #3

2022-12-08 16:09 UTC, skerbis commented
Als Reiter in YRewrite hätten die Redakteur:innen keinen Zugriff mehr auf die Einstellungen. Das sollen sie bei mir aber haben.

2022-12-08 16:12 UTC, skerbis requested changes
Als Reiter in YRewrite hätten die Redakteur:innen keinen Zugriff mehr auf die Einstellungen. Das sollen sie bei mir aber haben. Ein eigener Menüpunkt wäre da sicher ein Kompromiss. 

Meine Kunden sollen dort z.B. ihre Footer selbst pflegen oder auch mal das Logo und Kontaktdaten tauschen. Durch ein Verschieben in YRewrite hätten Sie keinen Zugriff mehr drauf weil dieses Admins vorbehalten ist.

2022-12-08 17:01 UTC, anveno commented
Verständlicher Einwand.

Alternativ zum eigenen Menüpunkt könnte man es auch in der install.php wieder auf "hidden": "0" setzen.
Und kann dann nach der Installation optional im Table Manager "In Navigation versteckt" aktivieren.

Aber eine eigene Seite ist vermutlich sinnvoller; evtl. "YRewrite Settings", so das es direkt unter "YRewrite" unter Addons erscheint?

2022-12-08 18:30 UTC, alxndr-w commented
Ansonsten nimmste halt meins 😉
https://github.com/alexplusde/yrewrite_metainfo/blob/25b95550c0325955d3e8dfaf8419562e415ef315/package.yml#L15-L17

Spaß beiseite, YRewrite soll ein eigenes Recht für den Hauptmenü-Punkt vergeben, dann kann man diesen aktivieren ohne den Rest: https://github.com/yakamara/redaxo_yrewrite/blob/6123eedde97ac2ab788633ead92b4ca3f5d0edc2/package.yml#L7-L16

2022-12-08 19:15 UTC, anveno commented
@alxndr-w 
Dein Addon scheint generell etwas aktueller zu sein. Allerdings ist mir das mit den vorbelgten Feldern und zusätzlichen Tabellen schon fast zu viel. So ein Zwischending wäre wahrscheinlich super, d.h. das man das optional importieren kann.

Nun denn. Habe hier gerade einen falschen zweiten Commit reingetüdelt... wie ziehe ich den Pull Request zurück?
Via "Close with comment" oder an welcher Stelle? Hab´s immer noch nicht so mit Git :/

2022-12-09 09:34 UTC, closed without merging

2022-12-09 09:35 UTC, skerbis commented
Hey ich wollte das nicht kaputt reden

2022-12-09 10:57 UTC, anveno commented
> Hey ich wollte das nicht kaputt reden

@skerbis Alles gut, habe es nur geschlossen da ich hier zwei verschiedene Sachen im Git vermischt habe - ich maches es nochmal sauber mit Branches. Muss mich hier erst reinfummeln.

2022-12-09 14:24 UTC, alxndr-w commented
Gerne erweitere ich euch noch dieses Domainauswahl-Feld für YForm um eine Sprachauswahl - beim nächsten mehrsprachigen Kunden. 

https://github.com/alexplusde/yform_field/blob/main/lib/yform/value/domain.php